CREATE TABLE IF NOT EXISTS NOBEL_PRIZE(
    YEAR INTEGER,
    SUBJECT TEXT,
    WINNER TEXT,
    COUNTRY TEXT,
    CATEGORY TEXT
);

INSERT INTO NOBEL_PRIZE(YEAR,SUBJECT,WINNER,COUNTRY,CATEGORY) VALUES
(1970,'PHYSICS','ABC','SWEDEN','SCIENTIST'),
(1970,'PHYSICS','EFG','FRANCE','SCIENTIST'),
(1971,'PHYSICS','HIJ','FRANCE','SCIENTIST'),
(1971,'CHEMISTRY','KLM','SWEDEN','LINGUIST'),
(1972,'LITERATURE','NOP','GERMANY','ECONOMIST'),
(1972,'ECONOMICS','QRS','RUSSIA','ECONOMIST'),
(1973,'BIOLOGY','TUV','USA','PRIME MINISTER'),
(1980,'BIOLOGY','WXY','USA','PRESIDENT'),
(1981,'PHYSIOLOGY','ZAB','HUNGARY','SCIENTIST'),
(1975,'PHYSICS','CDE','CHILE','SCIENTIST');

SELECT * FROM NOBEL_PRIZE WHERE SUBJECT NOT LIKE 'P%';
SELECT * FROM NOBEL_PRIZE ORDER BY COUNTRY DESC;
